// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFybxbeh6duDlaiO5futzkleNtSqSNDvc',
    appId: '1:419208201817:web:2122c26ab6d2e0e32c9348',
    messagingSenderId: '419208201817',
    projectId: 'nearrestaurants-75bd8',
    authDomain: 'nearrestaurants-75bd8.firebaseapp.com',
    storageBucket: 'nearrestaurants-75bd8.appspot.com',
    measurementId: 'G-GDM04LQEVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtN5BVeD94TbJXwQnvrXEcEFQXxAtaXQ4',
    appId: '1:419208201817:android:1968eed1a719a1ed2c9348',
    messagingSenderId: '419208201817',
    projectId: 'nearrestaurants-75bd8',
    storageBucket: 'nearrestaurants-75bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxacN3vW0xyG0fyE8NGy7AxFbHv_leHeA',
    appId: '1:419208201817:ios:521f4aed500d3ff12c9348',
    messagingSenderId: '419208201817',
    projectId: 'nearrestaurants-75bd8',
    storageBucket: 'nearrestaurants-75bd8.appspot.com',
    androidClientId: '419208201817-amkfvndhu9s8k4287tj8643ei0k27cri.apps.googleusercontent.com',
    iosClientId: '419208201817-n6gs1urercdno0ja3isqfpq88nmj7hmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearrestaurants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxacN3vW0xyG0fyE8NGy7AxFbHv_leHeA',
    appId: '1:419208201817:ios:521f4aed500d3ff12c9348',
    messagingSenderId: '419208201817',
    projectId: 'nearrestaurants-75bd8',
    storageBucket: 'nearrestaurants-75bd8.appspot.com',
    androidClientId: '419208201817-amkfvndhu9s8k4287tj8643ei0k27cri.apps.googleusercontent.com',
    iosClientId: '419208201817-n6gs1urercdno0ja3isqfpq88nmj7hmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearrestaurants',
  );
}
